-- Frozen alignment recipe contracts from the 2.0 definitions.
return {
  {name="nullius-broken-align-transponder",category="small-crafting",seconds=3,ingredients={{name="nullius-broken-align-transponder",amount=1},{name="nullius-iron-wire",amount=1}},products={{name="nullius-align-transponder",amount=1}}},
  {name="nullius-align-identification-card",category="tiny-crafting",seconds=8,ingredients={{name="nullius-steel-sheet",amount=1},{name="nullius-plastic",amount=1}},products={{name="nullius-align-identification-card",amount=1}}},
  {name="nullius-align-invitation-card",category="tiny-crafting",seconds=10,ingredients={{name="nullius-align-identification-card",amount=1},{name="nullius-glass",amount=1},{name="nullius-aluminum-sheet",amount=1}},products={{name="nullius-align-invitation-card",amount=1}}},
  {name="nullius-align-transponder",category="small-crafting",seconds=12,ingredients={{name="nullius-align-identification-card",amount=1},{name="constant-combinator",amount=1},{name="nullius-capacitor",amount=2}},products={{name="nullius-align-transponder",amount=1}}},
  {name="nullius-align-conscription-charge",category="nullius-electrolysis",seconds=10,ingredients={{name="nullius-align-invitation-card",amount=1},{name="nullius-align-transponder",amount=1},{name="nullius-capacitor",amount=4}},products={{name="nullius-align-conscription-charge",amount=3}}},
  {name="nullius-align-conscription-ray",category="small-crafting",seconds=20,ingredients={{name="power-switch",amount=1},{name="nullius-multi-tool-1",amount=1},{name="nullius-relay-1",amount=1}},products={{name="nullius-align-conscription-ray",amount=1}}},
  {name="nullius-align-conscription-turret",category="medium-crafting",seconds=30,ingredients={{name="nullius-align-conscription-ray",amount=2},{name="nullius-night-vision-1",amount=1},{name="nullius-transformer",amount=1},{name="nullius-bearing",amount=1},{name="nullius-missile-launcher",amount=2},{name="nullius-steel-beam",amount=6}},products={{name="nullius-align-conscription-turret",amount=1}}},
  {name="nullius-align-concordance-transmitter",category="large-crafting",seconds=60,ingredients={{name="nullius-align-conscription-turret",amount=3},{name="nullius-large-beacon-1",amount=2},{name="nullius-align-conscription-charge",amount=10}},products={{name="nullius-align-concordance-transmitter",amount=1}}},
  {name="nullius-align-concordance-satellite",category="huge-crafting",seconds=300,ingredients={{name="nullius-align-concordance-transmitter",amount=3},{name="nullius-large-beacon-2",amount=2},{name="nullius-satellite",amount=1}},products={{name="nullius-align-concordance-satellite",amount=1}}},
}
