-- Frozen production material and color contracts.
return {
  {name="nullius-terraforming-drone-grey",seconds=60,technology="nullius-terraforming-2",ingredients={{name="nullius-shallow-excavation-drone",amount=1},{name="nullius-construction-bot-3",amount=2},{name="rocket-fuel",amount=2},{name="nullius-box-land-fill-gravel",amount=200}}},
  {name="nullius-terraforming-drone-tan",seconds=60,technology="nullius-terraforming-2",ingredients={{name="nullius-shallow-excavation-drone",amount=1},{name="nullius-construction-bot-3",amount=2},{name="rocket-fuel",amount=2},{name="nullius-box-land-fill-sand",amount=200}}},
  {name="nullius-terraforming-drone-brown",seconds=60,technology="nullius-terraforming-2",ingredients={{name="nullius-shallow-excavation-drone",amount=1},{name="nullius-construction-bot-3",amount=2},{name="rocket-fuel",amount=2},{name="nullius-box-land-fill-bauxite",amount=200}}},
  {name="nullius-terraforming-drone-red",seconds=60,technology="nullius-terraforming-2",ingredients={{name="nullius-shallow-excavation-drone",amount=1},{name="nullius-construction-bot-3",amount=2},{name="rocket-fuel",amount=2},{name="nullius-box-land-fill-iron",amount=200}}},
  {name="nullius-terraforming-drone-beige",seconds=60,technology="nullius-terraforming-2",ingredients={{name="nullius-shallow-excavation-drone",amount=1},{name="nullius-construction-bot-3",amount=2},{name="rocket-fuel",amount=2},{name="nullius-box-land-fill-limestone",amount=200}}},
  {name="nullius-paving-drone-grey",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-grey",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-reinforced-concrete",amount=300}}},
  {name="nullius-paving-drone-white",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-beige",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-white-concrete",amount=300}}},
  {name="nullius-paving-drone-red",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-red",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-red-concrete",amount=300}}},
  {name="nullius-paving-drone-blue",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-beige",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-blue-concrete",amount=300}}},
  {name="nullius-paving-drone-yellow",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-tan",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-yellow-concrete",amount=300}}},
  {name="nullius-paving-drone-green",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-beige",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-green-concrete",amount=300}}},
  {name="nullius-paving-drone-purple",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-red",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-purple-concrete",amount=300}}},
  {name="nullius-paving-drone-brown",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-brown",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-brown-concrete",amount=300}}},
  {name="nullius-paving-drone-black",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-grey",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-black-concrete",amount=300}}},
  {name="nullius-paving-drone-hazard",seconds=25,technology="nullius-terraforming-3",ingredients={{name="nullius-terraforming-drone-tan",amount=1},{name="nullius-logistic-bot-3",amount=1},{name="rocket-fuel",amount=1},{name="nullius-box-hazard-concrete",amount=300}}},
}
