#!/usr/bin/env python3
"""Compare saved factory plans at explicit stages and production rates."""
import argparse
import json
from pathlib import Path

from plan_factorio_factory import TestFailure, material_consumption, update_markdown_section


def compare_plans(reports, spec):
    rows = []
    for stage_name in spec['stages']:
        for rate in spec['rates']:
            pair = []
            for label, report in reports.items():
                stages = [s for s in report['stages'] if s['name'] == stage_name]
                if len(stages) != 1:
                    raise TestFailure(f'{label}: expected one stage {stage_name}')
                plans = [p for p in stages[0]['plans'] if p['rate_per_minute'] == rate]
                if len(plans) != 1:
                    raise TestFailure(f'{label}: expected one rate {rate}')
                plan = plans[0]
                if plan['flow']['status'] != 'optimal' or plan['construction']['flow']['status'] != 'optimal':
                    raise TestFailure(f'{label}: flow and construction must be optimal')
                factory = plan['factory']
                pair.append({'planet': label, 'machines': factory['process_machines'],
                    'electric_grid_mw': factory['electric_grid_mw'],
                    'machines_by_type': factory['machines'],
                    'active_machine_equivalents': sum(m['active_equivalents'] for m in factory['machines'].values()),
                    'fuel_per_minute': factory['fuel_per_minute'],
                    'heat_mw': sum(factory['heat_demand_mw_by_minimum_temperature'].values()),
                    'demands_per_minute': plan['demands_per_minute'],
                    'research_packs': plan['research']['packs'],
                    'supply_hours': plan['base_research_supply_hours'],
                    'scheduled_hours': plan['research_schedule'].get('hours'),
                    'labs': plan['research_schedule'].get('lab_count'),
                    'material_input_per_minute': {p: material_consumption(plan, p) for p in spec.get('materials', [])},
                    'raw_per_minute': plan['flow']['raw_per_minute']})
            rows.append({'stage': stage_name, 'rate': rate, 'planets': pair,
                         'machine_ratio_second_to_first': pair[1]['machines'] / pair[0]['machines']})
    if spec.get('combined_stage'):
        for row in rows:
            if row['stage'] != spec['combined_stage']:
                continue
            for planet in row['planets']:
                parts = [r for r in rows if r['stage'] in spec['independent_stages'] and r['rate'] == row['rate']]
                if len(parts) != len(spec['independent_stages']):
                    raise TestFailure('combined comparison requires every independent stage')
                planet['separate_line_station_sum'] = sum(p['machines'] for r in parts for p in r['planets'] if p['planet'] == planet['planet'])
    return {'schema': 1, 'rows': rows, 'provenance': {k: r['provenance'] for k, r in reports.items()},
            'assumptions': {k: r['assumptions'] for k, r in reports.items()},
            'science_analysis': {k: r.get('science_analysis') for k, r in reports.items()}}


def markdown(comparison, spec):
    lines = ['# ' + spec['title'], '',
        'Generated by `tools/compare_factorio_factory_plans.py`.', '',
        *[line for note in spec['notes'] for line in (note, '')],
        '| Stage | Packs/min | Planet | Stations | Electric MW | Fuel/min | Process heat MW | Supply hours | Scheduled hours |',
        '|---|---:|---|---:|---:|---:|---:|---:|---:|']
    for row in comparison['rows']:
        for planet in row['planets']:
            time = lambda value: '-' if value is None else f'{value:.3f}'
            lines.append(f"| {row['stage']} | {row['rate']} | {planet['planet']} | {planet['machines']} | "
                f"{planet['electric_grid_mw']:.2f} | {planet['fuel_per_minute']:,.0f} | {planet['heat_mw']:.2f} | "
                f"{time(planet['supply_hours'])} | {time(planet['scheduled_hours'])} |")
    if spec.get("research_stage"):
        lines += ['', '## Research budget', '',
                  'Research includes the selected recipe and construction unlocks.', '',
                  '| Planet | Rate | Pack | Required count |', '|---|---:|---|---:|']
        for row in comparison['rows']:
            if row['stage'] != spec['research_stage'] or row['rate'] != spec['detail_rate']:
                continue
            for planet in row['planets']:
                for pack, count in planet['research_packs'].items():
                    lines.append(f"| {planet['planet']} | {row['rate']} | {pack} | {count:,.0f} |")
        lines += ['', '## Physics unlock alone', '',
                  '| Planet | Pack | Required count |', '|---|---|---:|']
        for label, analysis in comparison['science_analysis'].items():
            if analysis is None:
                raise TestFailure('science comparison requires science_analysis: ' + label)
            for budget in analysis['budgets']:
                if budget['boundary'] == 'physics-unlock':
                    for pack, row in budget['packs'].items():
                        lines.append(f"| {label} | {pack} | {row['total']:,.0f} |")
    lines += ['', '## Final science stations', '',
              'Box recipes output boxes. Unpack recipes output individual packs.', '',
              '| Planet | Stage | Rate | Recipe | Machine | Count | Output/min |',
              '|---|---|---:|---|---|---:|---:|']
    for label, analysis in comparison['science_analysis'].items():
        for row in analysis['production_lines']:
            if row['rate'] != spec['detail_rate'] or row['stage'] not in spec['stages']:
                continue
            for p in row['producers']:
                lines.append(f"| {label} | {row['stage']} | {row['rate']} | {p['recipe']} | "
                             f"{p['machine']} | {p['count']} | {p['output_per_minute']:.2f} |")
    if spec.get('combined_stage'):
        lines += ['', '## Combined and independent lines', '',
                  'The solver minimizes active time. Rounding a different route can increase the station count.',
                  'Separate lines remain a feasible station-count alternative; neither result proves the integer minimum.', '',
                  '| Planet | Rate per pack | Joint plan stations | Separate line station sum | Active equivalents in joint plan |',
                  '|---|---:|---:|---:|---:|']
        for row in comparison['rows']:
            if row['stage'] == spec['combined_stage']:
                for p in row['planets']:
                    lines.append(f"| {p['planet']} | {row['rate']} | {p['machines']} | {p['separate_line_station_sum']} | {p['active_machine_equivalents']:.2f} |")
    if spec.get('materials'):
        lines += ['', '## Gross material inputs', '',
                  'These are summed recipe inputs. They include internal circulation, not only net extraction.', '',
                  '| Planet | Stage | Rate | Material | Input/min |', '|---|---|---:|---|---:|']
        for row in comparison['rows']:
            if row['rate'] != spec['detail_rate']:
                continue
            for p in row['planets']:
                for material, amount in p['material_input_per_minute'].items():
                    lines.append(f"| {p['planet']} | {row['stage']} | {row['rate']} | {material} | {amount:.2f} |")
    if spec.get('machine_detail_stage'):
        lines += ['', '## Installed machines', '',
                  '| Planet | Machine | Count | Active equivalents |', '|---|---|---:|---:|']
        for row in comparison['rows']:
            if row['stage'] != spec['machine_detail_stage'] or row['rate'] != spec['detail_rate']:
                continue
            for planet in row['planets']:
                for name, machine in sorted(planet['machines_by_type'].items()):
                    lines.append(f"| {planet['planet']} | {name} | {machine['count']} | {machine['active_equivalents']:.2f} |")
    lines += ['', '## Declared boundaries', '']
    for label, assumptions in comparison['assumptions'].items():
        lines += ['### ' + label, '']
        lines += [f'- **{k}:** {v}' for k, v in assumptions.items()]
        lines.append('')
    return '\n'.join(lines).rstrip()


def update_vulcanus_capacity(comparison, path):
    lines = ["", "| Line | Packs/min each | Nauvis stations | Vulcanus stations | Nauvis electric MW | Vulcanus fuel gas/min | Vulcanus heat MW |",
             "|---|---:|---:|---:|---:|---:|---:|"]
    for row in comparison["rows"]:
        nauvis, vulcanus = row["planets"]
        lines.append(f"| {row['stage']} | {row['rate']} | {nauvis['machines']} | {vulcanus['machines']} | "
                     f"{nauvis['electric_grid_mw']:.2f} | {vulcanus['fuel_per_minute']:,.0f} | {vulcanus['heat_mw']:.2f} |")
    update_markdown_section(path, "tier2-capacity", "\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', type=Path, required=True)
    parser.add_argument('--first-plan', type=Path, required=True)
    parser.add_argument('--second-plan', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--markdown-output', type=Path)
    parser.add_argument('--update-vulcanus-doc', type=Path)
    args = parser.parse_args()
    spec = json.loads(args.config.read_text())
    reports = {label: json.loads(path.read_text()) for label, path in
               zip(spec['planets'], [args.first_plan, args.second_plan], strict=True)}
    if len(reports) != 2:
        raise TestFailure('comparison requires two distinct planet labels')
    result = compare_plans(reports, spec)
    args.output.write_text(json.dumps(result, indent=2) + '\n')
    if args.update_vulcanus_doc:
        update_vulcanus_capacity(result, args.update_vulcanus_doc)
    if args.markdown_output:
        args.markdown_output.write_text(markdown(result, spec) + '\n')
    print(json.dumps(result['rows'], indent=2))


if __name__ == '__main__':
    try:
        main()
    except (TestFailure, OSError, ValueError) as error:
        raise SystemExit(str(error))
