#!/usr/bin/env python3
"""Generate a deterministic Lua production contract for a Factorio scenario."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys
from typing import Any


REPOSITORY = Path(__file__).resolve().parents[1]
ANALYZER = REPOSITORY / "tools" / "analyze_factorio_prereqs.py"
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Lua scenario manifest from resolved Factorio prototypes."
    )
    parser.add_argument("args_file", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--timeout-seconds", type=int, default=300)
    return parser.parse_args()


def lua(value: Any, indent: int = 0) -> str:
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    prefix = "  " * indent
    child = "  " * (indent + 1)
    if isinstance(value, list):
        if not value:
            return "{}"
        entries = [f"{child}{lua(entry, indent + 1)}," for entry in value]
        return "{\n" + "\n".join(entries) + f"\n{prefix}}}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        entries = []
        for key in sorted(value):
            rendered_key = key if IDENTIFIER.match(key) else f"[{lua(key)}]"
            entries.append(
                f"{child}{rendered_key} = {lua(value[key], indent + 1)},"
            )
        return "{\n" + "\n".join(entries) + f"\n{prefix}}}"
    raise TypeError(f"unsupported manifest value: {type(value).__name__}")


def compact_step(step: dict[str, Any]) -> dict[str, Any]:
    fields = (
        "cycles",
        "executor",
        "fuel",
        "heat",
        "ingredients",
        "outputs",
        "producer",
        "product",
        "spoil_ticks",
        "ticks_per_cycle",
        "total_ticks_single_executor",
    )
    return {field: step[field] for field in fields if field in step}


def generate(args_file: Path, timeout_seconds: int) -> str:
    args_path = args_file.resolve()
    try:
        display_args = args_path.relative_to(REPOSITORY)
    except ValueError:
        display_args = args_path
    completed = subprocess.run(
        [sys.executable, str(ANALYZER), f"@{display_args}", "--json"],
        cwd=REPOSITORY,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=timeout_seconds,
        check=False,
    )
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip()
        raise RuntimeError(
            f"prerequisite analysis exited {completed.returncode}: {detail}"
        )
    report = json.loads(completed.stdout)
    manifest = report.get("production_manifest")
    if not isinstance(manifest, dict):
        raise RuntimeError("prerequisite report has no production manifest")
    if report.get("unresolved"):
        raise RuntimeError(f"manifest contains unresolved products: {report['unresolved']}")
    if report.get("required_technologies"):
        raise RuntimeError(
            "manifest requires undeclared technologies: "
            f"{report['required_technologies']}"
        )
    if manifest.get("available_inputs"):
        raise RuntimeError(
            "manifest requires undeclared consumable available inputs: "
            f"{manifest['available_inputs']}"
        )
    contract = {
        "schema": 1,
        "assumed_technologies": report["assumed_technologies"],
        "fuel_consumption": manifest["fuel_consumption"],
        "initial_stock": manifest["initial_stock"],
        "raw_inputs": manifest["raw_inputs"],
        "steps": [compact_step(step) for step in reversed(manifest["steps"])],
        "surplus": manifest["surplus"],
        "targets": manifest["targets"],
    }
    return (
        f"-- Generated by tools/generate_factorio_scenario_manifest.py\n"
        f"-- Source: {display_args}\n"
        f"return {lua(contract)}\n"
    )


def main() -> int:
    args = parse_arguments()
    try:
        rendered = generate(args.args_file, args.timeout_seconds)
        output = args.output.resolve()
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
                print(f"generated manifest is stale: {output}", file=sys.stderr)
                return 1
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        return 0
    except (OSError, RuntimeError, json.JSONDecodeError, subprocess.TimeoutExpired) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
