require("__nullius-star__/scenarios/vulcanus-manifest-runner"){
  case = "vulcanus-construction-closure",
  contract = require("manifest"),
  deadline = 270000,
  parallelism = 8,
  parallel_fixture = {
    ["nullius-seawater-intake-1"] = 6,
    ["nullius-hydro-plant-1"] = 4,
    ["nullius-small-furnace-1"] = 4,
    ["nullius-extractor-1"] = 6,
    ["nullius-air-filter-1"] = 6,
    ["nullius-distillery-1"] = 6,
    ["nullius-chemical-plant-1"] = 6,
    ["nullius-foundry-1"] = 4,
    ["nullius-small-assembler-1"] = 4,
  },
  fixture = {
    ["nullius-seawater-intake-1"] = 2,
    ["nullius-hydro-plant-1"] = 4,
    ["nullius-small-furnace-1"] = 4,
    pipe = 50,
    ["nullius-heat-pipe-1"] = 30,
    ["pipe-to-ground"] = 10,
    ["nullius-extractor-1"] = 2,
    ["nullius-air-filter-1"] = 2,
    ["nullius-distillery-1"] = 2,
    ["nullius-chemical-plant-1"] = 2,
    ["nullius-foundry-1"] = 4,
    ["nullius-small-assembler-1"] = 4,
    inserter = 12,
    ["iron-chest"] = 4,
    ["nullius-lab-1"] = 1,
    ["transport-belt"] = 50,
    splitter = 4,
    ["cliff-explosives"] = 30,
  },
}
