require("__nullius-star__/scenarios/vulcanus-manifest-runner"){
  case = "vulcanus-thermite",
  contract = require("manifest"),
  initial_technologies = {
    "nullius-explosives-1",
    "nullius-experimental-chemistry",
    "nullius-volcanic-alkali-processing",
    "nullius-pneumatic-technology",
  },
  deadline = 65000,
  parallelism = 8,
  scripted_heat = true,
  parallel_fixture = {
    ["nullius-seawater-intake-1"] = 7,
    ["nullius-hydro-plant-1"] = 7,
    ["nullius-air-filter-1"] = 3,
    ["nullius-distillery-1"] = 3,
    ["nullius-chemical-plant-1"] = 3,
    ["nullius-foundry-1"] = 7,
    ["nullius-medium-furnace-1"] = 7,
    ["nullius-small-assembler-1"] = 7,
    ["nullius-crusher-1"] = 3,
    ["nullius-barrel-pump-1"] = 1,
    ["nullius-vulcanus-radiator-1"] = 3,
    ["nullius-vulcanus-radiator-2"] = 3,
  },
  fixture = {
    ["nullius-seawater-intake-1"] = 1,
    ["nullius-hydro-plant-1"] = 1,
    ["nullius-air-filter-1"] = 1,
    ["nullius-distillery-1"] = 1,
    ["nullius-chemical-plant-1"] = 1,
    ["nullius-foundry-1"] = 1,
    ["nullius-medium-furnace-1"] = 1,
    ["nullius-small-assembler-1"] = 1,
    ["nullius-crusher-1"] = 1,
    ["nullius-barrel-pump-1"] = 1,
    ["nullius-vulcanus-radiator-1"] = 1,
    ["nullius-vulcanus-radiator-2"] = 1,
  },
}
